// packages/infrastructures/react_app/src/components/pokemon-form.tsx
import React, {
  FunctionComponent,
  useContext,
  useEffect,
  useState,
} from "react";
import { NavigateFunction, useNavigate } from "react-router";
import { formatType } from "../utils/formatType/formatType";
import { PokemonRequest } from "@pokemon/domain";
import { PokemonsPresenterVM } from "@pokemon/web-adapters";
import {
  DataProviderContext,
  dataProviderContextType,
} from "../context/DataProviderContext";
import { routesName } from "../utils/routing.config";

interface Props {
  id: string | undefined;
  pokemon: PokemonRequest;
}

interface Field {
  value?: any;
  error?: string;
  isValid?: boolean;
}

interface Form {
  picture: Field;
  name: Field;
  hp: Field;
  cp: Field;
  types: Field;
}

const PokemonForm: FunctionComponent<Props> = ({ id, pokemon }) => {
  const {
    getPokemonsController,
    updatePokemonController,
    addPokemonController,
    deletePokemonController,
  } = useContext(DataProviderContext) as dataProviderContextType;

  //On définit tous les types de pokémons
  const [types, setTypes] = useState<string[]>([]);

  useEffect(() => {
    getPokemonsController
      .getPokemons()
      .then((pokemonPresenter: PokemonsPresenterVM) =>
        setTypes(pokemonPresenter.pokemonTypes ?? []),
      );
  }, [getPokemonsController]);

  //On définit la variable isAddForm qui nous permettra de savoir si nous sommes en mode création de pokémon
  const isAddForm = !id;

  //On définit le hook qui va contenir les différentes informations du Pokémon à éditer: name, hp, cp et types.
  const [form, setForm] = useState<Form>({
    name: { value: pokemon.name, isValid: true },
    hp: { value: pokemon.hp, isValid: true },
    cp: { value: pokemon.cp, isValid: true },
    types: { value: pokemon.types, isValid: true },
    picture: { value: pokemon.picture, isValid: true },
  });

  const navigate: NavigateFunction = useNavigate(); //Méthode qui redirige ver la page à déclarer

  /**
   * Fonction qui checked les inputs dont le type figure dans les caractéristiques du pokémon à éditer
   * @param type type de pokémon
   */
  const hasType = (type: string): boolean => {
    return form.types.value.includes(type);
  };

  /**
   * Méthode qui update le formulaire à chaque changement effectuer par l'utilisateur
   * @param e événement
   */
  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const fieldName: string = e.target.name;
    const fieldValue: string = e.target.value;
    const newField: Field = { [fieldName]: { value: fieldValue } };

    //Spread Operator pour actualiser le formulaire
    setForm({ ...form, ...newField });
  };

  /**
   * Méthode pour update les types de pokémons
   * @param type type de pokémon
   * @param e événement
   */
  const selectType = (
    type: string,
    e: React.ChangeEvent<HTMLInputElement>,
  ): void => {
    const checked: boolean = e.target.checked;
    let newField: Field;

    if (checked) {
      const newTypes: string[] = form.types.value.concat([type]);
      newField = { value: newTypes };
    } else {
      const newTypes: string[] = form.types.value.filter(
        (currentType: string) => currentType !== type,
      );
      newField = { value: newTypes };
    }

    setForm({ ...form, ...{ types: newField } });
  };

  /**
   * Méthode de validité pour les types
   * @param type type de pokémon
   */
  const isTypesValid = (type: string): boolean => {
    if (form.types.value.length === 1 && hasType(type)) {
      return false;
    }

    return !(form.types.value.length >= 3 && !hasType(type));
  };

  /**
   * Méthode qui CREATE un pokémon
   * @param pokemon
   */
  const addPokemon = (pokemon: PokemonRequest): void => {
    addPokemonController
      .create(pokemon)
      .then(() => navigate(`/${routesName.pokemon.path}`));
  };

  /**
   * Méthode qui UPDATE un pokémon
   * @param pokemon
   */
  const updatePokemon = (pokemon: PokemonRequest): void => {
    updatePokemonController
      .update(id as string, pokemon)
      .then(() =>
        navigate(`/${routesName.pokemon.children.detail.fullPath}/${id}`),
      );
  };

  /**
   * Méthode qui DELETE un pokémon
   */
  const deletePokemon = (): void => {
    deletePokemonController
      .delete(id as string)
      .then(() => navigate(`/${routesName.pokemon.path}`));
  };

  /**
   * Méthode pour vérifier la validité des informations du formulaire (expressions régulières — regex)
   */
  const validateForm = async (): Promise<boolean> => {
    let newForm: Form = form;

    const [pictureError, nameError, hpError, cpError]: (string | undefined)[] =
      await Promise.all([
        updatePokemonController.validatePicture(form.picture.value),
        updatePokemonController.validateName(form.name.value),
        updatePokemonController.validateHp(form.hp.value),
        updatePokemonController.validateCp(form.cp.value),
      ]);

    //Validator picture
    if (isAddForm) {
      const pictureField: Field = {
        value: form.picture.value,
        error: pictureError,
        isValid: !pictureError,
      };
      newForm = { ...form, ...{ picture: pictureField } };
    }

    // Validator name
    const nameField: Field = {
      value: form.name.value,
      error: nameError,
      isValid: !nameError,
    };
    newForm = { ...newForm, ...{ name: nameField } };

    // Validator hp
    const hpField: Field = {
      value: form.hp.value,
      error: hpError,
      isValid: !hpError,
    };
    newForm = { ...newForm, ...{ hp: hpField } };

    // Validator cp
    const cpField: Field = {
      value: form.hp.value,
      error: cpError,
      isValid: !cpError,
    };
    newForm = { ...newForm, ...{ cp: cpField } };

    setForm(newForm);

    return Boolean(
      newForm.name.isValid &&
        newForm.hp.isValid &&
        newForm.cp.isValid &&
        newForm.picture.isValid,
    );
  };

  /**
   * Méthode pour gérer la soumission de notre formulaire
   * @param e événement
   */
  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const isFormValid: boolean = await validateForm();

    if (isFormValid) {
      //On actualise les paramètres du pokémon
      pokemon.name = form.name.value;
      pokemon.hp = form.hp.value;
      pokemon.cp = form.cp.value;
      pokemon.types = form.types.value;

      if (isAddForm) {
        pokemon.picture = form.picture.value;
        addPokemon(pokemon);
      } else {
        updatePokemon(pokemon);
      }
    }
  };

  return (
    <form onSubmit={(e) => handleSubmit(e)}>
      <div className="row">
        <div className="col s12 m8 offset-m2">
          <div className="card hoverable">
            {/* L'image ne s'affiche que si nous sommes en mode édition d'un pokémon */}
            {!isAddForm && (
              <div className="card-image">
                <img
                  src={pokemon.picture}
                  alt={pokemon.name}
                  style={{ width: "250px", margin: "0 auto" }}
                />
                <span className="btn-floating halfway-fab waves-effect waves-light">
                  <i onClick={deletePokemon} className="material-icons">
                    delete
                  </i>
                </span>
              </div>
            )}

            <div className="card-stacked">
              <div className="card-content">
                {/* Pokemon picture */}
                {isAddForm && (
                  <div className="form-group">
                    <label htmlFor="picture">Image</label>
                    <input
                      id="picture"
                      type="text"
                      className="form-control"
                      defaultValue={form.picture.value}
                      name="picture"
                      onChange={(e) => handleInputChange(e)}
                    ></input>
                    {/* Error picture */}
                    {form.picture.error && (
                      <div
                        className="card-panel red accent-1"
                        dangerouslySetInnerHTML={{ __html: form.picture.error }}
                      ></div>
                    )}
                  </div>
                )}

                {/* Pokemon name */}
                <div className="form-group">
                  <label htmlFor="name">Nom</label>
                  <input
                    id="name"
                    type="text"
                    className="form-control"
                    defaultValue={form.name.value}
                    name="name"
                    onChange={(e) => handleInputChange(e)}
                  ></input>
                  {/* Error name */}
                  {form.name.error && (
                    <div className="card-panel red accent-1">
                      {form.name.error}
                    </div>
                  )}
                </div>

                {/* Pokemon hp */}
                <div className="form-group">
                  <label htmlFor="hp">Point de vie</label>
                  <input
                    id="hp"
                    type="number"
                    className="form-control"
                    defaultValue={form.hp.value}
                    name="hp"
                    onChange={(e) => handleInputChange(e)}
                  ></input>
                  {/* Error hp */}
                  {form.hp.error && (
                    <div className="card-panel red accent-1">
                      {form.hp.error}
                    </div>
                  )}
                </div>

                {/* Pokemon cp */}
                <div className="form-group">
                  <label htmlFor="cp">Dégâts</label>
                  <input
                    id="cp"
                    type="number"
                    className="form-control"
                    defaultValue={form.cp.value}
                    name="cp"
                    onChange={(e) => handleInputChange(e)}
                  ></input>
                  {/* Error cp */}
                  {form.cp.error && (
                    <div className="card-panel red accent-1">
                      {form.cp.error}
                    </div>
                  )}
                </div>

                {/* Pokemon types */}
                <div className="form-group">
                  <label>Types</label>
                  {types.map((type) => (
                    <div key={type} style={{ marginBottom: "10px" }}>
                      <label>
                        <input
                          id={type}
                          type="checkbox"
                          className="filled-in"
                          defaultValue={type}
                          defaultChecked={hasType(type)}
                          onChange={(e) => selectType(type, e)}
                          disabled={!isTypesValid(type)}
                        ></input>
                        <span>
                          <p className={formatType(type)}>{type}</p>
                        </span>
                      </label>
                    </div>
                  ))}
                </div>
              </div>

              {/* Submit button */}
              <div className="card-action center">
                <button type="submit" className="btn">
                  {" "}
                  Valider
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </form>
  );
};

export default PokemonForm;

// packages/infrastructures/angular_app/src/app/shared/component/pokemon-form/pokemon-form.component.ts
import {
  AfterViewInit,
  Component,
  DestroyRef,
  inject,
  input,
  InputSignal,
  OnInit,
  signal,
  WritableSignal,
} from '@angular/core';
import {Router} from '@angular/router';
import {FormBuilder, FormGroup, ReactiveFormsModule,} from '@angular/forms';

import {LoaderComponent} from '../loader/loader.component';
import {PokemonTypeColorPipe} from '../../pipe/pokemon-type-color.pipe';
import {takeUntilDestroyed} from '@angular/core/rxjs-interop';
import {routesName} from '../../../app-routing-config';
import {combineLatest, concatMap, debounceTime, distinctUntilChanged, from, map, Observable, startWith} from 'rxjs';
import {Pokemon, PokemonRequest} from '@pokemon/domain';
import {AddedPokemonController, EditPokemonController} from '@pokemon/web-adapters';
import {DataSharedService} from '../../service/data-shared/data-shared.service';

@Component({
  selector: 'app-pokemon-form',
  standalone: true,
  templateUrl: './pokemon-form.component.html',
  styleUrl: './pokemon-form.component.scss',
  imports: [LoaderComponent, PokemonTypeColorPipe, ReactiveFormsModule],
})
export class PokemonFormComponent implements OnInit , AfterViewInit{
  pokemon: InputSignal<Pokemon> = input.required();

  private readonly router: Router = inject(Router);
  private readonly fb: FormBuilder = inject(FormBuilder);
  private readonly destroyRef: DestroyRef = inject(DestroyRef);
  private readonly dataShared: DataSharedService = inject(DataSharedService);
  private readonly addController: AddedPokemonController = inject(AddedPokemonController);
  private readonly editController: EditPokemonController = inject(EditPokemonController);

  formGroup: FormGroup;
  isAddForm: boolean = this.router.url.includes(routesName.pokemon.children.add.path);

  types: WritableSignal<string[]> = signal(this.dataShared.pokemonTypes);
  pokemonErrors: WritableSignal<PokemonErrors> = signal({
    hpError: undefined,
    cpError: undefined,
    nameError: undefined,
    pictureError: undefined,
  })

  ngOnInit() {
    this.formGroup = this.fb.group({
      id: [this.pokemon()?.id],
      hp: [this.pokemon()?.hp],
      cp: [this.pokemon()?.cp],
      name: [this.pokemon()?.name],
      picture: [this.pokemon()?.picture],
      types: [this.pokemon()?.types],
      created: [this.pokemon()?.created],
    });
  }

  ngAfterViewInit(): void {
    const controller = this.isAddForm ? this.addController : this.editController;
    this.formGroup.valueChanges.pipe(
      takeUntilDestroyed(this.destroyRef),
      debounceTime(200),
      distinctUntilChanged(),
      concatMap((formValue: any) => {
        return combineLatest([
          from(controller.validateName(formValue.name)).pipe(startWith(undefined)),
          from(controller.validateHp(formValue.hp)).pipe(startWith(undefined)),
          from(controller.validateCp(formValue.cp)).pipe(startWith(undefined)),
          from(controller.validatePicture(formValue.picture)).pipe(startWith(undefined)),
        ])
      }),
      map(([nameError, hpError, cpError, pictureError]) => ({nameError, hpError, cpError, pictureError} as PokemonErrors)),
    ).subscribe((pokemonErrors: PokemonErrors) => this.pokemonErrors.set(pokemonErrors))
  }

  /**
   * Cette méthode permet de cocher les types de pokemon présent dans la liste du pokémon courant.
   * @param type
   * @return boolean
   */
  hasType(type: string): boolean {
    const types: string[] = this.formGroup.get('types')?.value;
    return types.includes(type);
  }

  /**
   * Cette méthode permet d'ajouter ou retirer un type dans la liste des types d'un Pokemon
   * @param isChecked
   * @param type
   */
  selectType(isChecked: boolean, type: string): void {
    let types: string[] = this.formGroup.get('types')?.value;

    if (isChecked) {
      types = [...types, type];
    } else {
      types = types.filter((currentType: string) => currentType !== type);
    }

    this.formGroup.get('types')?.patchValue(types);
  }

  /**
   * Cette methode permet de griser les boutons de catégories si la liste des catégories du pokémon est égale à UN ou à 3.
   * @param type
   * @returns boolean
   */
  isTypesValid(type: string): boolean {
    const types: string[] = this.formGroup.get('types')?.value;
    if (types.length === 1 && this.hasType(type)) {
      return false;
    }
    return !(types.length > 2 && !this.hasType(type));
  }

  /**
   * Cette méthode ajoute ou édite un pokémon.
   */
  onSubmit($event: Event): void {
    $event.preventDefault();
    $event.stopImmediatePropagation();
    let observable$: Observable<Pokemon>;
    const pokemonRequest : PokemonRequest = {
      hp: this.formGroup.get('hp')?.value,
      cp: this.formGroup.get('cp')?.value,
      name: this.formGroup.get('name')?.value,
      picture: this.formGroup.get('picture')?.value,
      types: this.formGroup.get('types')?.value,
      created: this.formGroup.get('created')?.value,
    };

    if (this.isAddForm) {
      observable$ = from(this.addController.create(pokemonRequest));
    } else {
      observable$ = from(this.editController.update(this.pokemon().id, pokemonRequest));
    }

    observable$
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: (pokemon: Pokemon)=> {
          this.router.navigate([routesName.pokemon.children.detail.fullPath, pokemon.id]);
        },
        error: (errors: Map<string, string>)=> {
          const pokemonErrors: PokemonErrors = {
            hpError: errors.get('hp'),
            cpError: errors.get('cp'),
            nameError: errors.get('name'),
            pictureError: errors.get('picture'),
          };
          this.pokemonErrors.set(pokemonErrors);
        }
      });
  }
}

interface PokemonErrors {
  hpError: string | undefined;
  cpError: string | undefined;
  nameError: string | undefined;
  pictureError: string | undefined;
}

@if (pokemon()) {
  <form [formGroup]="formGroup" (ngSubmit)="onSubmit($event)">
    <div class="row">
      <div class="col s8 offset-s2">
        <div class="card-panel">
          <!-- Pokemon name -->
          <div class="form-group">
            <label for="name">Nom</label>
            <input
              type="text"
              class="form-control"
              id="name"
              autocomplete="false"
              formControlName="name"
            />
              @if (pokemonErrors().nameError) {
                <div class="card-panel red accent-1">
                  {{pokemonErrors().nameError}}
                </div>
              }
          </div>

          <!-- Pokemon Picture -->
          @if (isAddForm) {
            <div class="form-group">
              <label for="picture">Nom</label>
              <input
                type="url"
                class="form-control"
                id="picture"
                autocomplete="false"
                formControlName="picture"
              />
                @if (pokemonErrors().pictureError) {
                  <div class="card-panel red accent-1" [innerHTML]="pokemonErrors().pictureError">
                  </div>
                }
            </div>
          }

          <!-- Pokemon hp -->
          <div class="form-group">
            <label for="hp">Point de vie</label>
            <input
              type="number"
              class="form-control"
              id="hp"
              autocomplete="false"
              formControlName="hp"
            />
            @if (pokemonErrors().hpError) {
              <div class="card-panel red accent-1">
                {{ pokemonErrors().hpError }}
              </div>
            }
          </div>

          <!-- Pokemon cp -->
          <div class="form-group">
            <label for="cp">Dégâts</label>
            <input
              type="number"
              class="form-control"
              id="cp"
              autocomplete="false"
              formControlName="cp"
            />
              @if (pokemonErrors().cpError) {
                <div class="card-panel red accent-1">
                  {{pokemonErrors().cpError}}
                </div>
              }
          </div>

          <!-- Pokemon types -->
          <form class="form-group">
            <p>Types</p>
            @for (type of types(); track type) {
              <p>
                <label>
                  <input
                    type="checkbox"
                    class="filled-in"
                    [attr.id]="type"
                    [value]="type"
                    [checked]="hasType(type)"
                    [disabled]="!isTypesValid(type)"
                    (change)="selectType($any($event).target.checked, type)"
                  />
                  <span>
                    <div class="{{ type | pokemonTypeColor }}">
                      {{ type }}
                    </div>
                  </span>
                </label>
              </p>
            }
          </form>

          <!-- Submit button -->
          <div class="divider"></div>
          <div class="section center">
            <button type="submit" class="waves-effect waves-light btn">
              Valider
            </button>
          </div>
        </div>
      </div>
    </div>
  </form>
} @else {
  <h3 class="center">
    <app-loader></app-loader>
  </h3>
}
